services:
  runtime:
    build: ./docker
    volumes:
      - '../:/src'
      - './docker/run.sh:/home/docker/run.sh'
      - './scripts:/home/docker/scripts'
    ports:
      - 7681:7681
    command: ['./run.sh']

  playwright:
    depends_on:
      runtime:
        condition: service_healthy
    image: mcr.microsoft.com/playwright:v1.45.0-jammy@sha256:87742f12debf99873b69d166f6a02b8e7a6f47ddb51d9dfdb708849898fe11d1
    user: pwuser
    security_opt:
      - 'seccomp=./docker/playwright_seccomp_profile.json'
    ipc: host # Recommended when running chrome
    init: true
    environment:
      BASE_URL: 'http://runtime:7681'
      DOCKER: true
      NPM_CONFIG_UPDATE_NOTIFIER: 0 # Suppress npm new version message, since it's out of our control
    volumes:
      - './:/src'
    ports:
      - 9323:9323
    working_dir: /src
    command: tail -f /dev/null
