services:
  runtime:
    build: ./docker
    volumes:
      - '../:/src'
      - './docker/run.sh:/home/docker/run.sh'
      - './scripts:/home/docker/scripts'
    ports:
      - 7681:7681
    environment:
      DEBUG: '1'
    command: ['./run.sh']

  playwright:
    depends_on:
      runtime:
        condition: service_healthy
    image: mcr.microsoft.com/playwright:v1.48.1-jammy@sha256:8c8076751fb2936d5ca45eb75d5cfa1a6dc0e5b529f3643862649b7f0515bd3f
    user: pwuser
    security_opt:
      - 'seccomp=./docker/playwright_seccomp_profile.json'
    ipc: host # Recommended when running chrome
    init: true
    environment:
      BASE_URL: 'http://runtime:7681'
      DOCKER: true
      NPM_CONFIG_UPDATE_NOTIFIER: 0 # Suppress npm new version message, since it's out of our control
    volumes:
      - './:/src'
    ports:
      - 9323:9323
    working_dir: /src
    command: tail -f /dev/null
