name: E2E Tests
on:
  push:
    branches: [ "trunk" ]
  pull_request:

permissions:
  contents: read

jobs:
  e2e:
    name: Run E2E test
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=node-version depName=node
      NODE_VERSION: 20
    defaults:
      run:
        working-directory: e2e-test
    steps:
      - name: Setup repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: "${{env.NODE_VERSION}}"
          cache: 'npm'
          cache-dependency-path: e2e-test/package-lock.json

      - name: Install playwright deps
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run e2e tests
        run: ../bin/e2e

      - name: Output docker compose logs
        if: failure()
        run: docker compose logs

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: playwright-html-report
          path: e2e-test/playwright-report
          retention-days: 5
