name: E2E Tests
on:
  push:
    branches: [ "trunk" ]
  pull_request:

permissions:
  contents: read

jobs:
  e2e:
    name: Run E2E test
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=node-version depName=node
      NODE_VERSION: 16
    defaults:
      run:
        working-directory: e2e-test
    steps:
      - name: Setup repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: "${{env.NODE_VERSION}}"
          cache: 'npm'
          cache-dependency-path: e2e-test/package-lock.json

      - name: Install playwright deps
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run e2e tests
        run: ../bin/e2e

      - name: Output docker compose logs
        if: failure()
        run: docker compose logs

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4
        with:
          name: playwright-html-report
          path: e2e-test/playwright-report
          retention-days: 5
