name: CI
on:
  push:
    branches: [ "trunk" ]
  pull_request:

permissions:
  contents: read

jobs:
  CI:
    name: Lint, Typecheck & Test
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=denoland/deno
      DENO_VERSION: v1.44.2
    steps:
      - name: Setup repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "${{env.DENO_VERSION}}"

      - name: Run lint script
        run: ./bin/lint
