name: CI
on:
  push:
    branches: [ "trunk" ]
  pull_request:

permissions:
  contents: read

jobs:
  CI:
    name: Lint, Typecheck & Test
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=denoland/deno
      DENO_VERSION: v1.43.1
    steps:
      - name: Setup repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "${{env.DENO_VERSION}}"

      - name: Run lint script
        run: ./bin/lint
