name: CI
on:
  push:
    branches: [ "trunk" ]
  pull_request:

permissions:
  contents: read

jobs:
  CI:
    name: Lint, Typecheck & Test
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=denoland/deno
      DENO_VERSION: v2.0.0
    steps:
      - name: Setup repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "${{env.DENO_VERSION}}"

      - name: Run lint script
        run: ./bin/lint
