name: CI
on:
  push:
    # Check renovate/** to allow checks to run before it creates a PR
    branches: [ "trunk", "renovate/**" ]
  pull_request:

permissions:
  contents: read

jobs:
  CI:
    name: Lint, Typecheck & Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run lint script
        run: ./bin/lint
