name: CI
on:
  push:
    branches: ['trunk']
  pull_request:

permissions:
  contents: read

jobs:
  CI:
    name: Lint, Typecheck & Test
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=denoland/deno
      DENO_VERSION: v2.7.5
    steps:
      - name: Setup repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '${{env.DENO_VERSION}}'

      - name: Run lint script
        run: ./bin/lint
