name: CI
on:
  push:
    branches: [ "trunk" ]
  pull_request:

permissions:
  contents: read

jobs:
  CI:
    name: Lint, Typecheck & Test
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=denoland/deno
      DENO_VERSION: v1.43.6
    steps:
      - name: Setup repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "${{env.DENO_VERSION}}"

      - name: Run lint script
        run: ./bin/lint
