name: CI
on:
  push:
    branches: ['trunk']
  pull_request:

permissions:
  contents: read

jobs:
  CI:
    name: Lint, Typecheck & Test
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=denoland/deno
      DENO_VERSION: v2.5.6
    steps:
      - name: Setup repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '${{env.DENO_VERSION}}'

      - name: Run lint script
        run: ./bin/lint
