name: Publish
on:
  push:
    branches:
      - trunk

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=denoland/deno
      DENO_VERSION: v2.6.0
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '${{env.DENO_VERSION}}'

      - name: Publish
        run: deno publish
