name: Publish
on:
  push:
    branches:
      - trunk

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=denoland/deno
      DENO_VERSION: v2.2.8
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '${{env.DENO_VERSION}}'

      - name: Publish
        run: deno publish
