name: Publish
on:
  push:
    branches:
      - trunk

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=denoland/deno
      DENO_VERSION: v2.7.14
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: '${{env.DENO_VERSION}}'

      - name: Publish
        run: deno publish
